### ISSUE TITLE
Paste does not work in Firefox

### ISSUE THREAD

**Issue by abhineet97** [jgillich/faststack#18]
The shortcut for pasting text to the terminal, `Ctrl + Shift + v` (as specified [here]), does not seem to work for me.

My Browser: Firefox 50.0.2

[here]:https://termbox.io/help/terminal

**Comment by jgillich** [comment]
Firefox support in hterm isn't very good unfortunately.

**Comment by jgillich** [comment]
I've looked into this, the issue is that `document.execCommand('paste')` doesn't work in a browser environment, and hterm's workaround of focusing a textbox on Ctrl+Shift+V doesn't work in Firefox either.

Probably working as intended from a Firefox perspective, I doubt there's much we can do about it. Still going to leave it open, the user experience needs to be improved.
