### ISSUE TITLE
Alpine Linux is missing on https://termbox.io

### ISSUE THREAD

**Issue by jirutka** [jgillich/faststack#31]
There’s image for Alpine in this repository, but it’s not available on https://termbox.io. Why?

**Comment by jgillich** [comment]
It's intentionally disabled because it still needs a little tweaking.

**Comment by jirutka** [comment]
What exactly needs to be tweaked? I’m one of Alpine Linux developers, so maybe I can help with it.

**Comment by jgillich** [comment]
I took a look, here's what needs to be done:

- [x] The bash prompt variable wasn't setup properly, however we don't hardcode bash anymore, therefore I've changed it to use the default busybox shell.

- [ ] Rust is not available since Rustup doesn't support non-glibc systems and the package is still in testing. Definitely optional, but would be nice to have.

- [x] font-mfizz lacks a alpine icon (https://github.com/fizzed/font-mfizz/pull/49) and I'm not going to install the vbox kernel module for vagrant just to build it myself. [font-linux]( https://github.com/Lukas-W/font-linux) seems more maintained anyway so we should probably switch (~~but no alpine icon either as of now~~ https://github.com/Lukas-W/font-linux/pull/26)
- [x] The grid doesn't actually fit more than 6 distributions right now, so I'd need to update the frontend component

**Comment by Alhadis** [comment]
[Alpine Linux icon included here](https://github.com/file-icons/source/blob/master/svg/Alpine-Linux.svg). =)

**Comment by jgillich** [comment]
Thanks for the info, but I'd like to stick with just a single icon font for the distribution icons and font-linux looks much more complete for that purpose.

**Comment by jgillich** [comment]
Alpine will be included in the next iteration.
